In [1]:
import numpy as np
import pandas as pd
import xarray as xr
import matplotlib.pyplot as plt

import sys
sys.path.append('/home3/sreich/MITgcm_c68w/MITgcm/utils/python/MITgcmutils')
from MITgcmutils import rdmds

In [2]:
def read_float32(fileIn):
    with open(fileIn, 'rb') as f:
        data = np.fromfile(f, dtype=np.dtype('>f'))
        print(np.shape(data))
    return data

def read_float64(fileIn):
    with open(fileIn, 'rb') as f:
        data = np.fromfile(f, dtype=np.dtype('>f8'))
        print(np.shape(data))
    return data


In [3]:
run_dir = '/nobackup/sreich/llc270_c68w_runs/run_pk0000841536_obsfit_3/'

equi = xr.open_dataset(run_dir + 'swot_cycles_009_llc270_45_test_obsfit.equi.nc')
equi

<xarray.Dataset>
Dimensions:   (iOBS: 3345176)
Dimensions without coordinates: iOBS
Data variables:
    mod_val   (iOBS) float64 ...
    mod_mask  (iOBS) float64 ...

In [4]:
np.unique(equi.mod_val.values)

array([-1.49272167, -1.49252917, -1.49187026, ...,  0.01467769,
        0.01583708,         nan])

In [5]:
tile160 = read_float64(run_dir + 'swot_cycles_009_llc270_45_test_obsfit.081.001.equi.data')
np.unique(tile160)

(485328,)


array([0.])

## subset input datafile

In [6]:
#data_dir = '/nobackup/sreich/swot/swot_obsfit_L3/'
obs = xr.open_dataset(run_dir + 'swot_cycles_009_llc270_45_test_obsfit.nc')
obs

<xarray.Dataset>
Dimensions:               (iOBS: 3345176, iSAMPLE: 3345176, iINTERP: 8)
Dimensions without coordinates: iOBS, iSAMPLE, iINTERP
Data variables: (12/16)
    obs_date              (iOBS) float64 ...
    obs_YYYYMMDD          (iOBS) int64 ...
    obs_HHMMSS            (iOBS) int64 ...
    sample_x              (iSAMPLE) float64 ...
    sample_y              (iSAMPLE) float64 ...
    sample_z              (iSAMPLE) float64 ...
    ...                    ...
    sample_interp_YC11    (iOBS) float64 ...
    sample_interp_XCNINJ  (iOBS) float64 ...
    sample_interp_YCNINJ  (iOBS) float64 ...
    sample_interp_i       (iOBS) float64 ...
    sample_interp_j       (iOBS) float64 ...
    sample_interp_w       (iOBS, iINTERP) float64 ...

In [12]:
obs.sample_interp_XC11.values

array([-38.41825867, -38.41825867, -38.41825867, ...,  52.        ,
        52.        ,  52.        ])

In [7]:
sub = obs.isel(iOBS = range(100), iSAMPLE = range(100))
sub

<xarray.Dataset>
Dimensions:               (iOBS: 100, iSAMPLE: 100, iINTERP: 8)
Dimensions without coordinates: iOBS, iSAMPLE, iINTERP
Data variables: (12/16)
    obs_date              (iOBS) float64 ...
    obs_YYYYMMDD          (iOBS) int64 ...
    obs_HHMMSS            (iOBS) int64 ...
    sample_x              (iSAMPLE) float64 ...
    sample_y              (iSAMPLE) float64 ...
    sample_z              (iSAMPLE) float64 ...
    ...                    ...
    sample_interp_YC11    (iOBS) float64 ...
    sample_interp_XCNINJ  (iOBS) float64 ...
    sample_interp_YCNINJ  (iOBS) float64 ...
    sample_interp_i       (iOBS) float64 ...
    sample_interp_j       (iOBS) float64 ...
    sample_interp_w       (iOBS, iINTERP) float64 ...

In [14]:
#obs.to_netcdf(run_dir + 'swot_cycles_009_llc270_45_test_100_obsfit')

In [13]:
sub.sample_interp_XC11.values

array([-38.41825867, -38.41825867, -38.41825867, -38.41825867,
       -38.41825867, -38.41825867, -38.41825867, -38.41825867,
       -38.41825867, -38.41825867, -38.41825867, -38.41825867,
       -38.41825867, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83333397,
       -22.83333397, -22.83333397, -22.83333397, -22.83

In [14]:
xc = rdmds(run_dir + 'XC')
xc

array([[  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [-38.03704071, -38.05221558, -38.06198883, ..., -38.16666794,
        -38.16666794, -38.16666794],
       [-38.16666794, -38.16666794, -38.16666794, ..., -38.16666794,
        -38.16666794, -38.16666794],
       [-38.16666794, -38.16666794, -38.16666794, ...,   0.        ,
          0.        ,   0.        ]])

In [33]:
xc_flats = xc.flatten()

sub = obs.sample_interp_XC11.values[300000:400000]

tf = []
for i in range(len(sub)):
    tf.append(sub[i] in xc_flats)

In [34]:
np.unique(tf)

array([ True])

In [22]:
len(obs.sample_interp_XC11.values)

3345176